version: '3.8'

services:
  dev-api:
    build:
      context: dev-api/.
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      MONGO_URL: mongodb://localhost@mongo:27017
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
networks:
  app-network:
    driver: bridge
